version: 2.1

orbs:
  node: circleci/node@6.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build with vite
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
           - dist/
  deploy:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub pages
          command: |
            git config --global user.email "no-reply@timo-reymann.de"
            git config --global user.name "CircleCI Pipeline"
            echo "bookmarklet-generator.timo-reymann.de" > dist/CNAME
            npx gh-pages@2.0.1 --dist dist/ --message "docs: Update github pages [ci skip]"

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
